#!/bin/sh

# script/test: Run test suite for application.

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

go test -v ./... -covermode=count -coverprofile=coverage.out
go tool cover -func=coverage.out